services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - "POSTGRES_HOST_AUTH_METHOD: trust"
    ports:
      - '5433:5432'